### ISSUE TITLE
Wallet, dark theme highlighting menu

### ISSUE THREAD

**Issue by constantinos-yiasemi** [CybitsBlockchain/cybits-wallet#12]
Hey guys,

Mouse over / highlighting in the left menu should have a darker background colour 👌👍👍
 
![image](https://user-images.githubusercontent.com/71179427/142202694-11405e10-484e-4562-a17e-cd09d0c1ed84.png)

Thank you,

Constantinos

**Comment by psavva** [comment]
Fixed. Will be released in the next version
