### ISSUE TITLE
Feature Request - ToolTips on Icons

### ISSUE THREAD

**Issue by psavva** [CybitsBlockchain/cybits-wallet#9]
Create tooltips for all Icons.
This will help users navigate the UI a little easier, especially since it deafults to collapsed

**Comment by JeremyPaulCarroll** [comment]
A very small point, but because the app defaults to having the side menu collapsed, maybe tooltips would help for the icons?
The first thing I thought was 'what do these buttons do?' and I automatically hovered over them, expecting that it would tell me 🙂

**Comment by psavva** [comment]
This has been implemented, and will be included in the next release
